### ISSUE TITLE
Document `Name has been retired and cannot be reused`

### ISSUE THREAD

**Issue by jsoref** [github/docs#17617]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository

### What part(s) of the article would you like to see updated?

Something to explain `Name has been retired and cannot be reused`.

* Describe when it can happen.
* Is it truly permanent?
* Is there a way to avoid it?

### Additional information

* https://github.community/t/im-getting-this-error-name-has-been-retired-and-cannot-be-reused/238418
* https://github.community/t/after-the-acount-username-changed-the-repository-name-has-been-retired-and-cannot-be-reused/248716

**Comment by ramyaparimi** [comment]
@jsoref 
Thanks so much for opening an issue! I'll triage this for the team to review :eyes:

**Comment by janiceilene** [comment]
It looks like this was fixed in https://github.com/github/docs/pull/16181, so I'm going to close this issue now.

Thanks so much @jsoref 💖

**Comment by jsoref** [comment]
@janiceilene: that doesn't seem to be the right PR

**Comment by vgrl** [comment]
> @janiceilene: that doesn't seem to be the right PR

Thanks for catching this @jsoref , you're right—reopening as this issue still can be addressed.

**Comment by mervy93** [comment]
#20277
