### ISSUE TITLE
Example output is not visible

### ISSUE THREAD

**Issue by 0sf** [github/docs#26725]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#GitHub-flavored-markdown

In the Styling text section, Superscript doesn't provide an output text:
![Untitled design](https://github.com/github/docs/assets/16242676/11cb5251-8151-4283-a689-f9864e387772)

### What changes are you suggesting?

It will be easier if we provide an example combined with the normal text, like this:
![Screenshot_20230715_090634](https://github.com/github/docs/assets/16242676/c185cf21-8419-405f-81f6-b9221341c5b5)

**Comment by 0sf** [comment]
If possible I would like to work on this issue, Thank you for your consideration.

**Comment by vats147** [comment]
@0sf issue solved

**Comment by cmwilson21** [comment]
@0sf Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by hectorsector** [comment]
👋 @cmwilson21 @felicitymay I tried to review the PR but it looks like it's closed. Just ping if you'd like me to re-review or let's open an internal issue so we can fix this bug.

**Comment by felicitymay** [comment]
@hectorsector - thanks for your comment ✨ 

If you're able to look at the problem reported in this issue and determine what the correct solution is, that would be great.

It's not clear to me whether this is something that can/should be corrected by an OS contributor because any changes might have accessibility implications.

If the proposed solution in the closed PR is appropriate and doesn't cause any accessibility concerns, then we can ask the contributor to reopen their PR.

**Comment by hectorsector** [comment]
Reopened and approved the PR for engineering changes. Still needs a content review!

**Comment by 0sf** [comment]
Thank you for the approved PR.
However, It may seem like the last PR #26730 does not completely resolve the issue. there's a mismatch between the example code snippets and the output (kindly refer to the image).
 
![Untitled design](https://github.com/github/docs/assets/16242676/45309f7b-45f7-41ac-aa71-d68bc32efe10)

Please review a possible solution in PR #27252. 

![Screenshot_20230803_103905](https://github.com/github/docs/assets/16242676/1882f2b7-dc62-45c7-bd74-b719239e2066)

Thank you very much.

**Comment by felicitymay** [comment]
Thank you so much for checking this @0sf 

I clearly reviewed the previous PR in too much of a hurry 🤦🏻‍♀️ 

I'll go and look at your PR straight away 👀

**Comment by 0sf** [comment]
You are welcome @felicitymay, Yeah it's perfect now 😄 
Thank you again 🙏

**Comment by felicitymay** [comment]
I really enjoyed seeing you working together on fixing this issue @0sf and @vats147 💖 

It's a great example of open source collaboration 🥇

**Comment by 0sf** [comment]
That was definitely fun!  😍

Great job, @vats147, for proposing a solution in the first place. 👍 

Thanks, everyone 🙏

This inspires me to contribute more to open-source projects. 🎉
